### ISSUE TITLE
SuperCPU + REU issues

### ISSUE THREAD

**Issue by jpcompton** [johanberntsson/ozmoo#11]
_This is easier to replicate on VICE (and indeed may be demonstrating flaw[s] with VICE's SCPU emulation) but there is also some evidence that it happens on real hardware as well:_

While investigating a recent Dialog port I spotted an issue with Ozmoo + SuperCPU + REU preload.

On VICE, attempting to load the game will either produce an Ozmoo FATAL ERROR 8, or hard-crash (it forcibly quits) the emulator (every time, for me, MacOS latest public build r37694).

Testers with real hardware report that the game _sometimes_ loads and plays correctly, but at least one FATAL ERROR 8 has occurred, as well as some silent failures during load where the system simply freezes.

I do have an SCPU plus real REUs and am willing to dig them out if you wish to pursue this bug. Am also happy to join you in a bug report to the VICE team.

Recipe:

xscpu64
Machine: NTSC 64C
Enable 512k REU
Boot attached Ozmoo .d64
Answer Y when asked about REU

[craverly_dialz5.d64.zip](https://github.com/johanberntsson/ozmoo/files/4931786/craverly_dialz5.d64.zip)

**Comment by johanberntsson** [comment]
I can confirm that the problem appears in large game files using a combination of REU and SuperCPU. For some files it helps to reduce speed to 1MHz, but not all. Changing the memory mirroring options makes no difference. Running SuperCPU without REU works fine. A C64 without SuperCPU but with REU works fine. Not sure what the problem is, but we'll keep looking

**Comment by johanberntsson** [comment]
I can find reports of memory problems with the SuperCPU+REU combination in other projects as well, even on real hardware. Since no one is reporting a solution and anything I have tried is non-working we will give up. The solution which I have implemented is to always run without REU when a SuperCPU is detected. SuperCPU by itself (without REU) works.
