### ISSUE TITLE
Is a PET version feasible with 32K + 8K of RAM?

### ISSUE THREAD

**Issue by root42** [johanberntsson/ozmoo#68]
I have a 32K 40 column PET (upgraded 3016) with another 8K at 9000-AFFF, making a total of 40K of available RAM. I have a patched version of Bit Shifter's Z3 interpreter that uses the top 8K as a cache, which is great. However I wonder if the extra 8K would make ozmoo feasible on this platform, too? Obviously adjustments for the Kernal (BASIC 4.0) and IEEE488 disk routines might need to be done.

**Comment by fredrikr** [comment]
Thanks for the suggestion.

Yes, it's probably feasible.

We don't plan on adding this to Ozmoo, because (A) it would add complexity to the code base, and (B) the number of people interested in using it would likely be tiny. 

The main benefit that we could bring, compared to BitShifter's interpreter, is the ability to run z4 and z5 games, but pretty much all z4/z5 games would be crazy slow on a machine with only 40 KB of RAM anyway. While we could also support PETs with 64 KB and more RAM, these machines have a tricky banking scheme which would slow down games as well, *and* add complexity to the code base.
