### ISSUE TITLE
odd text input formatting

### ISSUE THREAD

**Issue by cfmoorz2** [johanberntsson/ozmoo#70]
first off. this is so cool.

but why does the text input behave like this (see screen capture)? 

this is using VICE emulator (the only one that seems to work on macos).

https://github.com/user-attachments/assets/c8157ba7-0546-418c-99c1-c92100c78a9e

**Comment by fredrikr** [comment]
It looks like you're running the emulator at much more than 100% speed, which means repeating keys repeat much faster. If you're running Vice in windowed mode, you should see a "100% CPU at" the bottom left when running at normalt speed.

Either:
(A) Press Ctrl-K to toggle key repeat on/off in Ozmoo
or
(B) Set a lower emulation speed. If you're in Warp Mode, you can press Alt-W to disable it. Otherwise, go to Preferences -> Emulation Speed to set it to 100%.

**Comment by cfmoorz2** [comment]
yes, i was running the emulator > 100% and, yes, turning off key repeat fixed it.

thx!
